// Code generated by internal/gen/types; DO NOT EDIT.

package client

// Supported type lists generated from the MisterShell OpenAPI spec
// (ui/openapi.json):
//   - SupportedResourceTypes   <- components.schemas.NetworkResourceType
//   - SupportedCredentialTypes <- components.schemas.CredentialType
//
// Regenerate with: make generate

// SupportedResourceTypes are the resource_type values accepted by the
// MisterShell backend.
var SupportedResourceTypes = []string{
	"aws_account",
	"azure_subscription",
	"cisco_ios",
	"cisco_iosxe",
	"cisco_iosxe_sdwan",
	"cisco_ise",
	"cisco_nxos",
	"cisco_vbond",
	"cisco_vmanage",
	"cisco_vsmart",
	"database",
	"generic_rdp",
	"generic_ssh",
	"infoblox_nios",
	"kubernetes_cluster",
	"linux",
	"panos_ssh",
	"windows",
}

// SupportedCredentialTypes are the credential_type values accepted by the
// MisterShell backend.
var SupportedCredentialTypes = []string{
	"aws_credentials",
	"azure_service_principal",
	"db_password",
	"kubeconfig",
	"rdp_password",
	"ssh_key",
	"ssh_password",
}
