// Code generated by internal/gen/types; DO NOT EDIT.

package client

// Supported type lists generated from the MisterShell OpenAPI spec
// (ui/openapi.json):
//   - SupportedResourceTypes          <- components.schemas.NetworkResourceType
//   - SupportedCredentialTypes        <- components.schemas.CredentialType
//   - SupportedLogDestinationTypes    <- LogDestinationCreate.properties.type
//   - SupportedLogStreams             <- LogDestinationCreate.properties.streams.items
//   - SupportedLogSeverities          <- LogDestinationCreate.properties.min_severity
//   - SupportedSyslogProtocols        <- SyslogConfig.properties.protocol
//   - SupportedSyslogFormats          <- SyslogConfig.properties.format
//   - SupportedSyslogFacilities       <- SyslogConfig.properties.facility
//   - SupportedWebhookMethods         <- WebhookConfig.properties.method
//   - SupportedWebhookBodyFormats     <- WebhookConfig.properties.body_format
//   - SupportedWebhookAuthTypes       <- WebhookConfig.properties.auth.discriminator.mapping
//   - SupportedAuthProviderTypes      <- AuthProviderCreate.properties.provider_type
//   - SupportedPolicyRuleActions      <- RuleCreate.properties.action
//   - SupportedSessionTypes           <- RuleCreate.properties.session_types.items
//   - SupportedAclPatternTypes        <- AclPattern.properties.type
//   - SupportedWorkerStatuses         <- WorkerStatus
//   - SupportedAIModelProviders       <- AIModelProvider
//   - SupportedAIPromptTypes          <- AIPromptType
//   - SupportedAIAgentTypes           <- AIAgentType
//
// Regenerate with: make generate

// SupportedResourceTypes are the resource_type values accepted by the
// MisterShell backend.
var SupportedResourceTypes = []string{
	"aws_account",
	"azure_subscription",
	"cisco_ios",
	"cisco_iosxe",
	"cisco_iosxe_sdwan",
	"cisco_ise",
	"cisco_nxos",
	"cisco_vbond",
	"cisco_vmanage",
	"cisco_vsmart",
	"database",
	"generic_rdp",
	"generic_ssh",
	"infoblox_nios",
	"kubernetes_cluster",
	"linux",
	"panos_ssh",
	"windows",
}

// SupportedCredentialTypes are the credential_type values accepted by the
// MisterShell backend.
var SupportedCredentialTypes = []string{
	"aws_credentials",
	"azure_service_principal",
	"db_password",
	"kubeconfig",
	"rdp_password",
	"ssh_key",
	"ssh_password",
}

// SupportedLogDestinationTypes are the log-destination type values.
var SupportedLogDestinationTypes = []string{
	"syslog",
	"webhook",
}

// SupportedLogStreams are the log-destination stream values.
var SupportedLogStreams = []string{
	"api",
	"app",
	"policy",
	"security",
}

// SupportedLogSeverities are the log-destination min_severity values.
var SupportedLogSeverities = []string{
	"critical",
	"high",
	"info",
	"low",
	"medium",
}

// SupportedSyslogProtocols are the syslog config protocol values (docs/anti-drift).
var SupportedSyslogProtocols = []string{
	"TCP",
	"TLS",
	"UDP",
}

// SupportedSyslogFormats are the syslog config format values (docs/anti-drift).
var SupportedSyslogFormats = []string{
	"CEF",
	"RFC3164",
	"RFC5424",
}

// SupportedSyslogFacilities are the syslog config facility values (docs/anti-drift).
var SupportedSyslogFacilities = []string{
	"local0",
	"local1",
	"local2",
	"local3",
	"local4",
	"local5",
	"local6",
	"local7",
}

// SupportedWebhookMethods are the webhook config method values (docs/anti-drift).
var SupportedWebhookMethods = []string{
	"POST",
	"PUT",
}

// SupportedWebhookBodyFormats are the webhook config body_format values (docs/anti-drift).
var SupportedWebhookBodyFormats = []string{
	"raw",
	"splunk_hec",
}

// SupportedWebhookAuthTypes are the webhook config auth.type values (docs/anti-drift).
var SupportedWebhookAuthTypes = []string{
	"basic",
	"bearer",
	"header",
	"none",
}

// SupportedAuthProviderTypes are the auth-provider provider_type values.
var SupportedAuthProviderTypes = []string{
	"LDAP",
	"OIDC",
	"SAML",
}

// SupportedPolicyRuleActions are the session-policy rule action values.
var SupportedPolicyRuleActions = []string{
	"accept",
	"deny",
}

// SupportedSessionTypes are the session-policy rule session_types item values.
var SupportedSessionTypes = []string{
	"graphical",
	"shell",
}

// SupportedAclPatternTypes are the session-policy ACL pattern type values.
var SupportedAclPatternTypes = []string{
	"glob",
	"regex",
}

// SupportedWorkerStatuses are the worker status values (read-only; docs/anti-drift).
var SupportedWorkerStatuses = []string{
	"error",
	"offline",
	"online",
	"pending",
}

// SupportedAIModelProviders are the ai_model provider values.
var SupportedAIModelProviders = []string{
	"anthropic",
	"azure_openai",
	"bedrock",
	"cohere",
	"google",
	"mistral",
	"ollama",
	"openai",
	"openrouter",
	"xai",
}

// SupportedAIPromptTypes are the ai_prompt type values (system, user).
var SupportedAIPromptTypes = []string{
	"system",
	"user",
}

// SupportedAIAgentTypes are the ai_agent type values (user-defined and builtin_*).
var SupportedAIAgentTypes = []string{
	"background",
	"builtin_background",
	"builtin_chat",
	"builtin_quick_action",
	"builtin_session_assist",
	"chat",
}
